config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('products.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('stores/', include('stores.urls'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from .views import category_details, product_details, home

urlpatterns = [
    path('', home, name='home'),
    path('categories/<int:category_id>/', category_details, name='category_details'),
    path('categories/<int:category_id>/<int:product_id>/', product_details, name='product_details'),

]

products/models.py
from django.db import models
from stores.models import Store
from django.utils.translation import ugettext_lazy as _


class Rating:
    VERY_BAD = '1'
    BAD = '2'
    MEDIUM = '3'
    GOOD = '4'
    VERY_GOOD = '5'

    @staticmethod
    def get_choices():
        return (
            (Rating.VERY_BAD, _('خیلی بد')),
            (Rating.BAD, _('بد')),
            (Rating.MEDIUM, _('متوسط')),
            (Rating.GOOD, _('خوب')),
            (Rating.VERY_GOOD, _('خیلی خوب'))
        )


class Category(models.Model):
    name = models.CharField(max_length=500, verbose_name=_('نام'), unique=True)
    slug = models.SlugField(unique=True, editable=False)
    description = models.TextField(verbose_name=_('توضیحات'), blank=True, null=True)
    image = models.ImageField(verbose_name=_('تصویر'), upload_to='products/category/image')
    order = models.IntegerField(verbose_name=_('ترتیب'), blank=True, null=True)

    class Meta:
        ordering = ['order', 'name']

    def __str__(self):
        return self.name

    def get_slug(self):
        slug = self.name.replace(' ', '-')
        return slug

    def save(self, *args, **kwargs):
        self.slug = self.get_slug()
        super(Category, self).save(*args, **kwargs)


class SubCategory(models.Model):
    name = models.CharField(max_length=500, verbose_name=_('نام'), unique=True)
    order = models.IntegerField(verbose_name=_('ترتیب'), blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name=_('دسته بندی'))

    class Meta:
        ordering = ['order', 'name']

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=1000, verbose_name=_('نام'))
    slug = models.SlugField(unique=True, editable=False)
    description = models.TextField(verbose_name=_('توضیحات'), blank=True, null=True)
    overview = models.TextField(verbose_name=_('توضیحات'), blank=True, null=True)
    price = models.IntegerField(verbose_name=_('قیمت'))
    # TODO : discount price
    quantity = models.IntegerField(verbose_name=_('تعداد'))
    number_of_buyers = models.IntegerField(verbose_name=_('تعداد خریداران'), default=0)
    rate = models.IntegerField(verbose_name=_('امتیاز'), blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.PROTECT, verbose_name=_('زیر دسته'))
    store = models.ForeignKey(Store, on_delete=models.CASCADE, verbose_name=_('فروشگاه'))

    # TODO: color and weight

    def __str__(self):
        return self.name

    def get_unique_slug(self):
        slug = self.name.replace(' ', '-')
        unique_slug = slug
        num = 1
        while Product.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        self.slug = self.get_unique_slug()
        super(Product, self).save(*args, **kwargs)


class ProductImage(models.Model):
    photo = models.ImageField(verbose_name=_('تصویر'), upload_to='products/category/image')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name=_('محصول'))

    def __str__(self):
        return self.product.name + " " + "IMAGE"

products/views.py
from django.shortcuts import render
from .models import Category, SubCategory, Product
from .filters import ProductFilter


def category_details(request, category_id):
    category = Category.objects.get(id=category_id)
    subcategories = SubCategory.objects.filter(category=category)
    products = ProductFilter(request.GET, category_id=category_id,
                             queryset=Product.objects.filter(subcategory__category=category))

    context = {
        'category': category,
        'subcategories': subcategories,
        'products': products
    }

    return render(request, 'products/category_details/category_details.html', context)


def product_details(request, category_id, product_id):
    category = Category.objects.get(id=category_id)
    product = Product.objects.get(id=product_id, subcategory__category=category)
    context = {
        'category': category,
        'product': product
    }
    return render(request, 'products/product_details/product_details.html', context)


def home(request):
    pass

products/templates/products/category_details/base.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'products/css/category_details.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'products/css/category_filter.css' %}">
{% endblock css %}

{% block js %}
    <script src="{% static 'products/js/category_details.js' %}"></script>
    <script src="{% static 'products/js/category_filter.js' %}"></script>

{% endblock js %}


{% block content %}
    <div class="row mx-xl-5">
        {% block breadcrumb %}
        {% endblock breadcrumb %}
    </div>
    <div class="row mx-xl-5 px-xl-5">
        <div class="col-12 mb-4">
            {% block page_title %}
            {% endblock page_title %}
        </div>
        <div class="col-md-3 mb-4">
                {% block filter %}
                {% endblock filter %}
        </div>

        {% block products %}
        {% endblock products %}

    </div>
{% endblock content %}

products/templates/products/category_details/category_details.html
{% extends 'products/category_details/base.html' %}

{% block title %}
    {{ category.name }}
{% endblock title %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">خانه</a></li>
            <li class="breadcrumb-item active" aria-current="page"> {{ category.name }}</li>
        </ol>
    </nav>
{% endblock breadcrumb %}
{% block page_title %}
    <h2 class="text-right">{{ category.name }}</h2>
    <p class="text-right">{{ category.description }}</p>
{% endblock page_title %}

{% block filter %}
    {% include 'products/category_details/category_filter.html' %}
{% endblock filter %}

{% block products %}
    <div class="col-md mr-3">
        <div class="row">
            {% for product in products.qs %}
                <div class="col-md-3 col-sm-4 col-6 pl-3 pr-0 pb-3">
                    <a href="{% url 'product_details' category.id product.id %}" class="link-card">
                        <div class="card shadow-sm text-right">
                            <img class="card-img-top" src="{{ product.productimage_set.first.photo.url }}">
                            <div class="card-body pb-0">
                                <h5 class="card-title text-primary text-truncate">{{ product.name }}</h5>
                                <p class="text-left mb-0">
                                    <span class="number price text-secondary">{{ product.price }}</span>
                                    <span class="toman text-secondary">تومان</span>
                                </p>
                                <div class="d-flex flex-wrap">
                                        <img src="{{ product.store.logo.url }}" class="rounded-circle  store-logo ml-2 mb-1">
                                        <p class="store-name text-truncate text-muted mb-1">{{ product.store.name }}</p>
                                </div>
                                <div class="d-flex flex-wrap" style="line-height: 1em;direction: ltr;">
                                    <i class="fas fa-star text-warning"></i>
                                    <i class="fas fa-star text-warning"></i>
                                    <i class="fas fa-star text-warning"></i>
                                    <i class="fas fa-star text-warning"></i>
                                    <i class="fas fa-star-half-alt text-warning"></i>

                                    <p class="number ratings nowrap ml-1">(102 نفر)</p>
                                </div>

                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock products %}

products/templates/products/category_details/category_filter.html
{% load staticfiles %}


<div class="card text-right shadow-sm mb-4">
    <h5 class="card-header">دسته بندی نتایج</h5>
    <div class="card-body pr-5">
        <h5 class="card-title"><i class="fas fa-angle-down ml-1"></i><a>{{ category.name }}</a></h5>
        <form action="" method="get">
            <div class="form-group">
                {% for choice in products.form %}
                    {% if forloop.counter < 2 %}
                        {{ choice }}
                    {% endif %}
                {% endfor %}
            </div>
        </form>
    </div>
</div>
{#<div class="card shadow-sm mb-4 text-right">#}
{#    <h5 class="card-header">محدوده قیمت</h5>#}
{#    <div class="card-body">#}
{#        <form action="" method="get">#}
{#            <div class="form-group">#}
{#                {% for choice in products.form.price %}#}
{#                    {{ choice }}#}
{#                {% endfor %}#}
{#            </div>#}
{#        <input type="submit">#}
{#        </form>#}
{#    </div>#}
{##}
{#</div>#}