config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('products.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('stores/', include('stores.urls'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stores/urls.py
from django.urls import path

from .views import create_store, validate_store_name, add_store_details, add_store_logo, add_store_cover, add_store_policy

urlpatterns = [
    path('create/', create_store, name='create_store'),
    path('create/validate_name/', validate_store_name, name='validate_store_name'),
    path('create/<store_id>/details/', add_store_details, name='add_store_details'),
    path('create/<store_id>/details/logo/', add_store_logo, name='add_store_logo'),
    path('create/<store_id>/details/cover/', add_store_cover, name='add_store_cover'),
    path('create/<store_id>/policy', add_store_policy, name='add_store_policy'),

]

stores/models.py
from django.db import models
from accounts.models import Profile
from django.utils.translation import ugettext_lazy as _


class ShippingMethod(models.Model):
    name = models.CharField(max_length=500, verbose_name=_('نام'))
    icon = models.ImageField(upload_to='products/shipping_method', verbose_name=_('تصویر'))


class Store(models.Model):
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=500, verbose_name=_('نام فروشگاه'), unique=True)
    slug = models.SlugField(unique=True, editable=False)
    logo = models.ImageField(verbose_name=_('لوگوی فروشگاه'), upload_to='products/store/logo', null=True, blank=True)
    city = models.CharField(max_length=500, verbose_name=_('شهر'))
    # TODO : cover could be gif or video :D
    cover_image = models.ImageField(verbose_name=_('تصویر کاور'), upload_to='products/store/cover', null=True,
                                    blank=True)
    # TODO : add emojies to text editor
    description = models.TextField(verbose_name=_('توضیحات'), blank=True, null=True)
    creation_date = models.DateTimeField(verbose_name=_('تاریخ ایجاد'), auto_now_add=True)

    # TODO : total_rate
    # TODO : total buyers
    class Meta:
        verbose_name = _('فروشگاه')
        verbose_name_plural = _('فروشگاه ها')

    def __str__(self):
        return self.name

    def get_slug(self):
        slug = self.name.replace(' ', '-')
        return slug

    def save(self, *args, **kwargs):
        self.slug = self.get_slug()
        super(Store, self).save(*args, **kwargs)


class Shipping(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE, verbose_name=_('فروشگاه'))
    shipping_method = models.OneToOneField(ShippingMethod, on_delete=models.CASCADE, verbose_name=_('شیوه ارسال'))
    price_store_city = models.CharField(max_length=7, default='0')
    price_other = models.CharField(max_length=7, default='0')


class Policy(models.Model):
    store = models.OneToOneField(Store, on_delete=models.CASCADE)

    return_policy = models.BooleanField(choices=((True, _('امکان پس گرفتن کالا وجود دارد')),
                                                 (False, _('امکان پس گرفتن کالا وجود ندارد'))), default=True)
    return_policy_description = models.CharField(max_length=500, blank=True, null=True)

    exchange_policy = models.BooleanField(choices=((True, _('امکان تعویض کالا وجود دارد')),
                                                   (False, _('امکان تعویض کالا وجود ندارد'))), default=True)
    exchange_policy_description = models.CharField(max_length=500, blank=True, null=True)

    cancellation_policy = models.BooleanField(choices=((True, _('امکان لغو سفارش وجود دارد')),
                                                       (False, _('امکان لغو سفارش وجود ندارد'))), default=True)
    cancellation_policy_description = models.CharField(max_length=500, blank=True, null=True)
    further_description = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return self.store.name + 'POLICIES'

stores/forms.py
from django import forms
from .models import Store, Policy


class StorePrimaryInfoForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = ['name', 'city']


class PolicyForm(forms.ModelForm):
    class Meta:
        model = Policy
        fields = ['return_policy', 'return_policy_description', 'exchange_policy', 'exchange_policy_description',
                  'cancellation_policy', 'cancellation_policy_description', 'further_description']
        widgets = {
            'return_policy': forms.RadioSelect,
            'exchange_policy': forms.RadioSelect,
            'cancellation_policy': forms.RadioSelect
        }

stores/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .forms import StorePrimaryInfoForm, PolicyForm
from .models import Store


@login_required
def create_store(request):
    if request.method == 'POST':
        form = StorePrimaryInfoForm(request.POST)
        if form.is_valid():
            store = form.save(commit=False)
            store.profile = request.user.profile
            store.save()
            return redirect('add_store_details', store_id=store.pk)

    form = StorePrimaryInfoForm()
    return render(request, 'stores/create_store/create_store_level1.html', {'form': form})


def validate_store_name(request):
    name = request.GET.get('store_name', None)
    validate = {'is_taken': Store.objects.filter(name__iexact=name).exists()}
    if validate['is_taken']:
        validate['error_message'] = 'فروشگاه با این نام وجود دارد.'

    return JsonResponse(validate)


def add_store_details(request, store_id):
    if request.method == 'POST':
        store = Store.objects.get(id=store_id)
        store.description = request.POST['description']
        store.save()
        return redirect('add_store_policy', store_id=store_id)
    return render(request, 'stores/create_store/create_store_level2.html', {'store_id': store_id})


def add_store_logo(request, store_id):
    store = Store.objects.get(id=store_id)
    if request.method == 'POST':
        store.logo = request.FILES['file']
        store.save()
        return JsonResponse({})


def add_store_cover(request, store_id):
    store = Store.objects.get(id=store_id)
    if request.method == 'POST':
        store.cover_image = request.FILES['file']
        store.save()
        return JsonResponse({})


def add_store_policy(request, store_id):
    store = Store.objects.get(id=store_id)
    if request.method == 'POST':
        form = PolicyForm(request.POST)
        if form.is_valid():
            policy = form.save(commit=False)
            policy.store = store
            policy.save()
            return redirect('signup')
    form = PolicyForm()
    return render(request, 'stores/create_store/create_store_level3.html', {'form': form})

stores/templates/stores/create_store/base.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'stores/css/create_store.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bower_components/dropzone/dist/min/dropzone.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bower_components/dropzone/dist/min/basic.min.css' %}">

{% endblock css %}

{% block js %}
    <script src="{% static 'stores/js/create_store_form1.js' %}"></script>
    <script src="{% static 'bower_components/dropzone/dist/min/dropzone.min.js' %}"></script>
    <script src="{% static 'stores/js/create_store_form2.js' %}"></script>

{% endblock js %}


{% block content %}
    <div class="row mx-xl-5 px-xl-5 pt-5 mt-3 justify-content-center">
        <div class="col-8 mb-5">
            {% block progress_bar %}
            {% endblock progress_bar %}
        </div>
        <div class="col-md-6 mb-4">
            {% block form_card %}
            {% endblock form_card %}
        </div>
    </div>
{% endblock content %}

stores/templates/stores/create_store/create_store_level1.html
{% extends 'stores/create_store/base.html' %}


{% block progress_bar %}
    <div class="progress" style="height: 30px;">
        <div class="progress-bar border-white border-left active" role="progressbar" style="width: 20%;font-size: 15px;"
             aria-valuenow="20" aria-valuemin="0"
             aria-valuemax="100">
            <span class="text-white"><i class="fas fa-store text-white"></i>
            اطلاعات اصلی فروشگاه</span>
        </div>
        <div class="progress-bar border-white border-left" role="progressbar" style="width: 20%;font-size: 15px;"
             aria-valuenow="20"
             aria-valuemin="0"
             aria-valuemax="100">
            <span class="text-white"><i class="fas fa-images text-white" style="font-size: 18px"></i>
            سایر اطلاعات فروشگاه</span>
        </div>
        <div class="progress-bar border-white border-left" role="progressbar" style="width: 20%;font-size: 15px;"
             aria-valuenow="20"
             aria-valuemin="0"
             aria-valuemax="100">
            <span class="text-white"><i class="fas fa-scroll text-white"></i>
            قوانین و مقررات</span>
        </div>
        <div class="progress-bar border-white border-left" role="progressbar" style="width: 20%;font-size: 15px;"
             aria-valuenow="20"
             aria-valuemin="0"
             aria-valuemax="100">
            <span class="text-white"><i class="fas fa-store text-white"></i>
            اطلاعات اصلی فروشگاه</span>
        </div>
        <div class="progress-bar" role="progressbar" style="width: 20%;font-size: 15px;" aria-valuenow="20"
             aria-valuemin="0"
             aria-valuemax="100">
            <span class="text-white"><i class="fas fa-store text-white"></i>
            اطلاعات اصلی فروشگاه</span>
        </div>
    </div>
{% endblock progress_bar %}

{% block form_card %}
    <div class="card shadow text-right">
        <div class="card-header mx-5 mt-1">
            <h3 class="text-center">اطلاعات اصلی فروشگاه</h3>
        </div>
        <div class="card-body px-5">
            <p>نام فروشگاه و شهر محل فروشگاه را وارد نمایید.</p>
            <form method="post" novalidate>
                {% csrf_token %}
                {% include 'stores/create_store/forms/form_level1.html' %}
                <div class="row justify-content-center">
                    <div class="col-4">
                        <button type="submit" class=" mt-2 btn btn-primary btn-lg btn-block">ذخیره و ادامه</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
{% endblock form_card %}

stores/templates/stores/create_store/create_store_level2.html
{% extends 'stores/create_store/base.html' %}


{% block progress_bar %}
    <div class="progress" style="height: 30px;">
        <div class="progress-bar border-white border-left active" role="progressbar" style="width: 20%;font-size: 15px;"
             aria-valuenow="20" aria-valuemin="0"
             aria-valuemax="100">
            <span class="text-white"><i class="fas fa-store text-white"></i>
            اطلاعات اصلی فروشگاه</span>
        </div>
        <div class="progress-bar border-white border-left active" role="progressbar" style="width: 20%;font-size: 15px;"
             aria-valuenow="20"
             aria-valuemin="0"
             aria-valuemax="100">
            <span class="text-white"><i class="fas fa-images text-white" style="font-size: 18px"></i>
            سایر اطلاعات فروشگاه</span>
        </div>
        <div class="progress-bar border-white border-left" role="progressbar" style="width: 20%;font-size: 15px;"
             aria-valuenow="20"
             aria-valuemin="0"
             aria-valuemax="100">
            <span class="text-white"><i class="fas fa-scroll text-white"></i>
            قوانین و مقررات</span>
        </div>
        <div class="progress-bar border-white border-left" role="progressbar" style="width: 20%;font-size: 15px;"
             aria-valuenow="20"
             aria-valuemin="0"
             aria-valuemax="100">
            <span class="text-white"><i class="fas fa-store text-white"></i>
            اطلاعات اصلی فروشگاه</span>
        </div>
        <div class="progress-bar" role="progressbar" style="width: 20%;font-size: 15px;" aria-valuenow="20"
             aria-valuemin="0"
             aria-valuemax="100">
            <span class="text-white"><i class="fas fa-store text-white"></i>
            اطلاعات اصلی فروشگاه</span>
        </div>
    </div>
{% endblock progress_bar %}

{% block form_card %}
    <div class="card shadow text-right">
        <div class="card-header mx-5 mt-1">
            <h3 class="text-center">سایر اطلاعات فروشگاه</h3>
        </div>
        <div class="card-body px-5">
            <p>تصویر لوگو، تصویر کاور و توضیحات مربوط به فروشگاه را وارد نمایید.</p>
            <div class="d-flex flex-row">
                <div class="d-flex flex-column ml-5 flex-fill">
                    <p class="mt-4">لوگوی فروشگاه:</p>
                    <form method="post" action="{% url 'add_store_logo' store_id %}"
                          class="dropzone"
                          enctype="multipart/form-data" id="myDropzone1" novalidate>
                        {% csrf_token %}

                    </form>
                </div>
                <div class="d-flex flex-column flex-fill">
                    <p class="mt-4">تصویر کاور فروشگاه:</p>
                    <br>
                    <form method="post" action="{% url 'add_store_cover' store_id %}"
                          class="dropzone"
                          enctype="multipart/form-data" id="myDropzone2" novalidate>
                        {% csrf_token %}

                    </form>
                </div>
            </div>
            <div class="d-flex flex-column">
                <form method="post" id="store-desc" novalidate>
                    {% csrf_token %}
                    <div class="form-group">
                        <p class="mt-4">شرح فعالیت فروشگاه:</p>
                        <textarea class="form-control" name="description" id="id_description" rows="10"></textarea>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-4">
                            <button type="submit" class=" mt-2 btn btn-primary btn-lg btn-block">ذخیره و ادامه</button>
                        </div>
                    </div>
                </form>
            </div>


        </div>
    </div>
{% endblock form_card %}

stores/templates/stores/create_store/create_store_level3.html
{% extends 'stores/create_store/base.html' %}


{% block progress_bar %}
    <div class="progress" style="height: 30px;">
        <div class="progress-bar border-white border-left active" role="progressbar" style="width: 20%;font-size: 15px;"
             aria-valuenow="20" aria-valuemin="0"
             aria-valuemax="100">
            <span class="text-white"><i class="fas fa-store text-white"></i>
            اطلاعات اصلی فروشگاه</span>
        </div>
        <div class="progress-bar border-white border-left  active" role="progressbar" style="width: 20%;font-size: 15px;"
             aria-valuenow="20"
             aria-valuemin="0"
             aria-valuemax="100">
            <span class="text-white"><i class="fas fa-images text-white" style="font-size: 18px"></i>
            سایر اطلاعات فروشگاه</span>
        </div>
        <div class="progress-bar border-white border-left active" role="progressbar" style="width: 20%;font-size: 15px;"
             aria-valuenow="20"
             aria-valuemin="0"
             aria-valuemax="100">
            <span class="text-white"><i class="fas fa-scroll text-white"></i>
            قوانین و مقررات</span>
        </div>
        <div class="progress-bar border-white border-left" role="progressbar" style="width: 20%;font-size: 15px;"
             aria-valuenow="20"
             aria-valuemin="0"
             aria-valuemax="100">
            <span class="text-white"><i class="fas fa-store text-white"></i>
            اطلاعات اصلی فروشگاه</span>
        </div>
        <div class="progress-bar" role="progressbar" style="width: 20%;font-size: 15px;" aria-valuenow="20"
             aria-valuemin="0"
             aria-valuemax="100">
            <span class="text-white"><i class="fas fa-store text-white"></i>
            اطلاعات اصلی فروشگاه</span>
        </div>
    </div>
{% endblock progress_bar %}

{% block form_card %}
    <div class="card shadow text-right">
        <div class="card-header mx-5 mt-1">
            <h3 class="text-center">اطلاعات اصلی فروشگاه</h3>
        </div>
        <div class="card-body px-5">
            <p>نام فروشگاه و شهر محل فروشگاه را وارد نمایید.</p>
            <form method="post" novalidate>
                {% csrf_token %}
                {% include 'stores/create_store/forms/form_level1.html' %}
                <div class="row justify-content-center">
                    <div class="col-4">
                        <button type="submit" class=" mt-2 btn btn-primary btn-lg btn-block">ذخیره و ادامه</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
{% endblock form_card %}